### PR TITLE
Some updates from minor to adding rules

### PR DESCRIPTION
**Pull request by devkale**

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi Aditya,

well done: thanks.
Before merging the pull request, it would be nice if you could:
1) Add your name in the list of contributors! :)
2) Add a test for the rule in the tests directory
3) Implement also part1 and change the name of the rule. It's easy to do. FunctionDecl isthe motherclass of CXXMethodDecl: http://clang.llvm.org/doxygen/classclang_1_1FunctionDecl.html . Using the Clang RTTI (namely llvm::isa<T>) you can check wether ou are dealing with a free function or a method and act accordingly.

**Comment by devkale** [comment]
Dear sir,
Today I have some assignments from my coursework. I will discuss and make changes tomorrow.
Thanks & Regards

**Comment by dpiparo** [comment]
Hi Aditya,

thanks for informing me. Looking forward.

D

On 03.02.2015 08:53, devkale wrote:
>
> Dear sir,
> Today I have some assignments from my coursework. I will discuss and 
> make changes tomorrow.
> Thanks & Regards
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dpiparo/SAS/pull/8#issuecomment-72608591>.
>

-- 
------------------------------------------------------------------------
   Danilo Piparo
   CERN PH-SFT
   Office: 32-R-C09
   Telephone: +41 (0)22 76 79 652
   Fax:    +41 (0)22 76 67 669
------------------------------------------------------------------------

**Comment by dpiparo** [comment]
Hi Aditya,

I looked more closely to the rules and your change. Indeed it is correct to factorise rule9 as you did. so points 1 and 2 are still valid. I'll merge the request afterwards. It would be nice to have "part2" changed into something more meaningful such as "Functions" so to have something more expressive like RN9Functions and, later, "RN9Attributes".

Cheers,
      D

**Comment by devkale** [comment]
Dear sir,
Before adding further rules, I will learn handling github from command line. Above changes are made using GitHub.com web interface, which is not efficient.
Thanks & Regards

**Comment by devkale** [comment]
Dear sir,
I have done changes mentioned by you. Updated test file. Please have a look.
Thanks & Regards

**Pull request merged**
