### PR TITLE
test harness

### PR DESCRIPTION
**Pull request by zhengyangl**
Hi danilo,

I've created a test harness for SAS. It uses a python script to launch the checker and do the output match, Now I have implemented 6 tests for CodingConvention and ThreadSafety checkers. 2 failed for some unknown reasons. I will fix them and port all the existing test into harness tomorrow :-)

    23:48:51 zhengyangl ~/research/static-analysis/SAS-env/SASBuild  $ ctest
    Test project /home/zhengyangl/research/static-analysis/SAS-env/SASBuild
         Start 1: sas.CodingConventions.ROOT.RN3
    1/6 Test #1: sas.CodingConventions.ROOT.RN3 .....   Passed    6.60 sec
         Start 2: sas.CodingConventions.ROOT.allRN
    2/6 Test #2: sas.CodingConventions.ROOT.allRN ...   Passed    0.16 sec
        Start 3: sas.ThreadSafety.ConstCastAway
    3/6 Test #3: sas.ThreadSafety.ConstCastAway .....   Passed    3.40 sec
        Start 4: sas.ThreadSafety.ConstCast
    4/6 Test #4: sas.ThreadSafety.ConstCast .........   Passed    3.50 sec
        Start 5: sas.ThreadSafety.GlobalStatic
    5/6 Test #5: sas.ThreadSafety.GlobalStatic ......***Failed    3.52 sec
        Start 6: sas.ThreadSafety.StaticLocal
    6/6 Test #6: sas.ThreadSafety.StaticLocal .......***Failed    3.50 sec
    
    67% tests passed, 2 tests failed out of 6
    
    Total Test time (real) =  20.70 sec
    
    The following tests FAILED:
              5 - sas.ThreadSafety.GlobalStatic (Failed)
              6 - sas.ThreadSafety.StaticLocal (Failed)
    Errors while running CTest

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi Zhengyang,

nice. I'll then merge the changes when you are done.

Cheers,
     Danilo

**Comment by zhengyangl** [comment]
Hi, Danilo,

I've created tests for all checkers in ThreadSafety, CodingConventions, Performances. I need to rewrite the rest of checkers(Varname, CatchAll, and ClassDumper) into new style before I finish creating tests for them. Tomorrow I'll finish all the tests.

screenshot 2015-04-21 00 11 17

**Comment by dpiparo** [comment]
Hi Zhengyang,

this looks very good.
Catchall and classdumper are really low priority and in first approximation can be considered legacy. If you want we can proceed with the finalisation of the tests with the varname checker and tag. This is the tag I'll propose for continuous integration and upload of results in CDash.

**Comment by zhengyangl** [comment]
Hi @dpiparo , test for varname finished:-)

**Comment by dpiparo** [comment]
Hi Zhengyang,

nice code: I merged the pull request, tested it and added two small commits. I must say the direction is really the right one: now it is straightforward to build and test SAS!
I have to minor comments nevertheless, which can further improve the testing. They do not require much additional work:
1) Instead of checking just the presence of the name of the checker in the output, what one could do is to compare the full output, once the paths to the input files have been removed (this can be done easily with python, replace function of string). For example, in case of the static_local output one could have this "universal output", i.e. stripped of the paths which are specific of the user's directory structure*.
2) The add_test CMake function could be replaced by something more specific: sas_add_test. This new cmake function would for example set all the parameters common to all the tests in order to avoid repetitions (which always cause mistakes, e.g. copy paste). In addition, this function could be extracted and put in a separate file located in the cmake directory.

Cheers,
    Danilo

*
```
test/ThreadSafety/static_local.cpp:10:9: warning: [sas.ThreadSafety.StaticLocalChecker] Non-const variable 'evilStaticLocal' is local static and might be thread-unsafe

        static int evilStaticLocal = 0;

        ^

test/ThreadSafety/static_local.cpp:10:9: note: [sas.ThreadSafety.StaticLocalChecker] Non-const variable 'evilStaticLocal' is local static and might be thread-unsafe

test/ThreadSafety/static_local.cpp:11:9: warning: [sas.ThreadSafety.StaticLocalChecker] Non-const variable 'intRef' is local static and might be thread-unsafe

        static int & intRef = evilStaticLocal;

        ^

test/ThreadSafety/static_local.cpp:11:9: note: [sas.ThreadSafety.StaticLocalChecker] Non-const variable 'intRef' is local static and might be thread-unsafe

test/ThreadSafety/static_local.cpp:12:2: warning: [sas.ThreadSafety.StaticLocalChecker] Non-const variable 'intPtr' is local static and might be thread-unsafe

        static int * intPtr = & evilStaticLocal;

        ^

test/ThreadSafety/static_local.cpp:12:2: note: [sas.ThreadSafety.StaticLocalChecker] Non-const variable 'intPtr' is local static and might be thread-unsafe

test/ThreadSafety/static_local.cpp:20:9: warning: [sas.ThreadSafety.StaticLocalChecker] Non-const variable 'threadLocal' is local static and might be thread-unsafe

        static int threadLocal = 0;

        ^

test/ThreadSafety/static_local.cpp:20:9: note: [sas.ThreadSafety.StaticLocalChecker] Non-const variable 'threadLocal' is local static and might be thread-unsafe

4 warnings generated.
```

**Comment by zhengyangl** [comment]
Okay, working on it.

**Pull request merged**
