### PR TITLE
make clang script more flexible

### PR DESCRIPTION
**Pull request by zhengyangl**
#4

### CODE REVIEW

**Comment by zhengyangl** [comment]
I used FindLLVM and sed to locate clang/clang++/clang-format and modify the scripts

**Comment by zhengyangl** [comment]
#18

**Comment by dpiparo** [comment]
Hi,

I refactored a bit the testing. Now we check for the full output of the test and we lowered the threshold for adding a test for a checker.
Let me know if this works for you. After this I will tag and push everything to continuous integration.

**Comment by zhengyangl** [comment]
Hi, @dpiparo 

It works for me :-)

**Pull request merged**
